version: 2
log-fle: /home/gisen/efm_langserver.log
log-level: 1
root-markers:
  - .git/
tools:
  yaml-yamllint: &yaml-yamllint
    lint-command: "yamllint -f parsable ${INPUT}"
    lint-stdin: true
  xmllint: &xmllint
    lint-command: "xmllint --noout --schema http://download.ros.org/schema/package_format2.xsd --valid ${INPUT}"
    lint-stdin: true
  xmllint: &xmlformat
    format-command: "xmllint --format --schema http://download.ros.org/schema/package_format2.xsd ${INPUT}"
    format-stdin: true
  roslaunchlint: &roslaunchlint
    lint-command: "xmllint --noout --schema /home/gisen/.config/xmllint/roslaunch.xsd --valid ${INPUT}"
    lint-stdin: true
  roslaunchformat: &roslaunchformat
    format-command: "xmllint --format --schema /home/gisen/.config/xmllint/roslaunch.xsd -"
    format-stdin: true
  cmakeformat: &cmakeformat
    format-command: "/home/gisen/.local/bin/cmake-format -c /home/gisen/.config/.cmake-format -l error ${INPUT}"
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: "flake8 --ignore=F401,W503 --max-line-length 119 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
  vim-vint: &vim-vint
    lint-command: "vint ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
  markdown-textlint: &markdown-textlint
    lint-command: 'npx --no-install textlint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%trror/%r]'
    root-markers:
      - .textlintrc
  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s -c %HOME%/.markdownlintrc'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f:%l:%c %m'
      - '%f: %l: %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: '/home/gisen/go/bin/shfmt -i 2 -ci -s -bn'
    format-stdin: true

languages:
  yaml:
    - <<: *yaml-yamllint
  xml:
    - <<: *xmllint
    - <<: *xmlformat
  roslaunch.xml:
    - <<: *roslaunchlint
    - <<: *roslaunchformat
  cmake:
    - <<: *cmakeformat
  python:
    - <<: *python-flake8
    # - <<: *python-mypy
    # - <<: *python-autopep8
    # - <<: *python-yapf
    # - <<: *python-black
    # - <<: *python-isort
  vim:
    - <<: *vim-vint
  markdown:
    - <<: *markdown-textlint
    - <<: *markdown-markdownlint
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

