version: 2
log-fle: /home/gisen/efm_langserver.log
log-level: 1
root-markers:
  - .git/
tools:
  yaml-yamllint: &yaml-yamllint
    lint-command: "yamllint -f parsable ${INPUT}"
    lint-stdin: true
  xmllint: &xmllint
    lint-command: "xmllint --noout --valid ${INPUT}"
    lint-stdin: true
  cmakeformat: &cmakeformat
    # lint-command: "cmake-format -c $HOME/.config/.cmake-format ${INPUT}"
    lint-command: "cmake-lint ${INPUT} -c $HOME/.config/.cmake-format"
    lint-stdin: true
  python-flake8: &python-flake8
    lint-command: "flake8 --ignore=F401,W503 --max-line-length 119 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
  vim-vint: &vim-vint
    lint-command: "vint ${INPUT}"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  yaml:
    - <<: *yaml-yamllint
  xml:
    - <<: *xmllint
  cmake:
    - <<: *cmakeformat
  python:
    - <<: *python-flake8
    # - <<: *python-mypy
    # - <<: *python-autopep8
    # - <<: *python-yapf
    # - <<: *python-black
    # - <<: *python-isort
  vim:
    - <<: *vim-vint
