
[".vim/bundle/Vundle.vim"]
    type = "git-repo"
    url = "https://github.com/VundleVim/Vundle.vim"
    refreshPeriod = "168h"
    [".vim/bundle/Vundle.vim".pull]
        args = ["--ff-only"]

[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/share/i3blocks-contrib"]
    type = "git-repo"
    url = "https://github.com/vivien/i3blocks-contrib"
    refreshPeriod = "168h"

[".local/share/my-template"]
    type = "git-repo"
    url = "https://github.com/h-wata/my-template"
    refreshPeriod = "168h"

[".config/eskk/SKK-JISYO.L"]
    type = "file"
    url = "https://github.com/skk-dev/dict/raw/master/SKK-JISYO.L"
    refreshPeriod = "168h"

[".local/share/fonts/'Roboto Mono Regular Nerd Font Complete.ttf'"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Regular/RobotoMonoNerdFont-Regular.ttf"
    refreshPeriod = "168h"

[".local/share/fonts/nerd-fonts"]
    type = "git-rep"
    url = "https://github.com/ryanoasis/nerd-fonts.git"
    refreshPeriod = "168h"
